-- as user deegree
CREATE TABLE administrativeboundary (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    country_attr_nilreason text,
    country_country text,
    country_country_attr_codelist text,
    country_country_attr_codelistvalue text,
    country_country_attr_codespace text,
    legalstatus text,
    legalstatus_attr_nilreason text,
    legalstatus_attr_nil boolean,
    technicalstatus text,
    technicalstatus_attr_nilreason text,
    technicalstatus_attr_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    CONSTRAINT administrativeboundary_pkey PRIMARY KEY (gid)
);
SELECT ADDGEOMETRYCOLUMN('', 'administrativeboundary','geometry_value','0','GEOMETRY', 2);
CREATE TABLE administrativeboundary_nationallevel (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    fk text,
    href text
);
CREATE TABLE administrativeboundary_admunit (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE administrativeunit (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    nationalcode text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    nationallevel_attr_owns boolean,
    nationallevel_attr_nilreason text,
    nationallevel_attr_remoteschema text,
    nationallevel_fk text,
    nationallevel_href text,
    country_attr_nilreason text,
    country_country text,
    country_country_attr_codelist text,
    country_country_attr_codelistvalue text,
    country_country_attr_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    upperlevelunit_attr_owns boolean,
    upperlevelunit_attr_nilreason text,
    upperlevelunit_attr_remoteschema text,
    upperlevelunit_attr_nil boolean,
    upperlevelunit_fk text,
    upperlevelunit_href text,
    CONSTRAINT administrativeunit_pkey PRIMARY KEY (gid)
);
SELECT ADDGEOMETRYCOLUMN('', 'administrativeunit','geometry_value','0','GEOMETRY', 2);
CREATE TABLE administrativeunit_nationallevelname (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_type text,
    attr_href text,
    attr_role text,
    attr_arcrole text,
    attr_title text,
    attr_show text,
    attr_actuate text,
    attr_uuidref text,
    attr_nilreason text,
    attr_nil boolean,
    localisedcharacterstring text,
    localisedcharacterstring_attr_id text,
    localisedcharacterstring_attr_locale text
);
CREATE TABLE administrativeunit_name (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    geographicalname_language text,
    geographicalname_language_attr_nilreason text,
    geographicalname_language_attr_nil boolean,
    geographicalname_nativeness_attr_owns boolean,
    geographicalname_nativeness_attr_nilreason text,
    geographicalname_nativeness_attr_remoteschema text,
    geographicalname_nativeness_attr_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_attr_owns boolean,
    geographicalname_namestatus_attr_nilreason text,
    geographicalname_namestatus_attr_remoteschema text,
    geographicalname_namestatus_attr_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_attr_nilreason text,
    geographicalname_sourceofname_attr_nil boolean,
    geographicalname_pronunciation_attr_nilreason text,
    geographicalname_pronunciation_attr_nil boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_7 text,
    geographicalname_pronunciation_pronunciationofname_pronun_8 text,
    geographicalname_pronunciation_pronunciationofname_pronun_9 boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_10 text,
    geographicalname_pronunciation_pronunciationofname_pronun_11 text,
    geographicalname_pronunciation_pronunciationofname_pronun_12 boolean,
    geographicalname_grammaticalgender_attr_owns boolean,
    geographicalname_grammaticalgender_attr_nilreason text,
    geographicalname_grammaticalgender_attr_remoteschema text,
    geographicalname_grammaticalgender_attr_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_attr_owns boolean,
    geographicalname_grammaticalnumber_attr_nilreason text,
    geographicalname_grammaticalnumber_attr_remoteschema text,
    geographicalname_grammaticalnumber_attr_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text
);
CREATE TABLE administrativeunit_name_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit_name ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_attr_nilreason text,
    geographicalname_spellingofname_script_attr_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_att_13 text,
    geographicalname_spellingofname_transliterationscheme_attr_nil boolean
);
CREATE TABLE administrativeunit_residenceofauthority (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_nil boolean,
    residenceofauthority_name_geographicalname_language text,
    residenceofauthority_name_geographicalname_language_attr__14 text,
    residenceofauthority_name_geographicalname_language_attr_nil boolean,
    residenceofauthority_name_geographicalname_nativeness_att_15 boolean,
    residenceofauthority_name_geographicalname_nativeness_att_16 text,
    residenceofauthority_name_geographicalname_nativeness_att_17 text,
    residenceofauthority_name_geographicalname_nativeness_attr_nil boolean,
    residenceofauthority_name_geographicalname_nativeness_fk text,
    residenceofauthority_name_geographicalname_nativeness_href text,
    residenceofauthority_name_geographicalname_namestatus_att_18 boolean,
    residenceofauthority_name_geographicalname_namestatus_att_19 text,
    residenceofauthority_name_geographicalname_namestatus_att_20 text,
    residenceofauthority_name_geographicalname_namestatus_attr_nil boolean,
    residenceofauthority_name_geographicalname_namestatus_fk text,
    residenceofauthority_name_geographicalname_namestatus_href text,
    residenceofauthority_name_geographicalname_sourceofname text,
    residenceofauthority_name_geographicalname_sourceofname_a_21 text,
    residenceofauthority_name_geographicalname_sourceofname_a_22 boolean,
    residenceofauthority_name_geographicalname_pronunciation__23 text,
    residenceofauthority_name_geographicalname_pronunciation__24 boolean,
    residenceofauthority_name_geographicalname_pronunciation__26 text,
    residenceofauthority_name_geographicalname_pronunciation__27 text,
    residenceofauthority_name_geographicalname_pronunciation__28 boolean,
    residenceofauthority_name_geographicalname_pronunciation__29 text,
    residenceofauthority_name_geographicalname_pronunciation__30 text,
    residenceofauthority_name_geographicalname_pronunciation__31 boolean,
    residenceofauthority_name_geographicalname_grammaticalgen_39 boolean,
    residenceofauthority_name_geographicalname_grammaticalgen_40 text,
    residenceofauthority_name_geographicalname_grammaticalgen_41 text,
    residenceofauthority_name_geographicalname_grammaticalgen_42 boolean,
    residenceofauthority_name_geographicalname_grammaticalgen_43 text,
    residenceofauthority_name_geographicalname_grammaticalgen_44 text,
    residenceofauthority_name_geographicalname_grammaticalnum_45 boolean,
    residenceofauthority_name_geographicalname_grammaticalnum_46 text,
    residenceofauthority_name_geographicalname_grammaticalnum_47 text,
    residenceofauthority_name_geographicalname_grammaticalnum_48 boolean,
    residenceofauthority_name_geographicalname_grammaticalnum_49 text,
    residenceofauthority_name_geographicalname_grammaticalnum_50 text,
    residenceofauthority_geometry_attr_nilreason text,
    residenceofauthority_geometry_attr_remoteschema text,
    residenceofauthority_geometry_attr_owns boolean,
    residenceofauthority_geometry_attr_nil boolean
);
CREATE TABLE administrativeunit_residenceofauthority_residenceofauthor_32 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit_residenceofauthority ON DELETE CASCADE,
    num integer not null,
    residenceofauthority_name_geographicalname_spellingofname_text text,
    residenceofauthority_name_geographicalname_spellingofname_33 text,
    residenceofauthority_name_geographicalname_spellingofname_34 text,
    residenceofauthority_name_geographicalname_spellingofname_35 boolean,
    residenceofauthority_name_geographicalname_spellingofname_36 text,
    residenceofauthority_name_geographicalname_spellingofname_37 text,
    residenceofauthority_name_geographicalname_spellingofname_38 boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'administrativeunit_residenceofauthority','residenceofauthority_geometry_value','0','GEOMETRY', 2);
CREATE TABLE administrativeunit_condominium (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE administrativeunit_lowerlevelunit (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_remoteschema text,
    attr_owns boolean,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE administrativeunit_administeredby (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE administrativeunit_coadminister (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE administrativeunit_boundary (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES administrativeunit ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE condominium (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    CONSTRAINT condominium_pkey PRIMARY KEY (gid)
);
CREATE TABLE condominium_name (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES condominium ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_nil boolean,
    geographicalname_language text,
    geographicalname_language_attr_nilreason text,
    geographicalname_language_attr_nil boolean,
    geographicalname_nativeness_attr_owns boolean,
    geographicalname_nativeness_attr_nilreason text,
    geographicalname_nativeness_attr_remoteschema text,
    geographicalname_nativeness_attr_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_attr_owns boolean,
    geographicalname_namestatus_attr_nilreason text,
    geographicalname_namestatus_attr_remoteschema text,
    geographicalname_namestatus_attr_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_attr_nilreason text,
    geographicalname_sourceofname_attr_nil boolean,
    geographicalname_pronunciation_attr_nilreason text,
    geographicalname_pronunciation_attr_nil boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_0 text,
    geographicalname_pronunciation_pronunciationofname_pronun_1 text,
    geographicalname_pronunciation_pronunciationofname_pronun_2 boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_3 text,
    geographicalname_pronunciation_pronunciationofname_pronun_4 text,
    geographicalname_pronunciation_pronunciationofname_pronun_5 boolean,
    geographicalname_grammaticalgender_attr_owns boolean,
    geographicalname_grammaticalgender_attr_nilreason text,
    geographicalname_grammaticalgender_attr_remoteschema text,
    geographicalname_grammaticalgender_attr_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_attr_owns boolean,
    geographicalname_grammaticalnumber_attr_nilreason text,
    geographicalname_grammaticalnumber_attr_remoteschema text,
    geographicalname_grammaticalnumber_attr_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text
);
CREATE TABLE condominium_name_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES condominium_name ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_attr_nilreason text,
    geographicalname_spellingofname_script_attr_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_att_6 text,
    geographicalname_spellingofname_transliterationscheme_attr_nil boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'condominium','geometry_value','0','GEOMETRY', 2);
CREATE TABLE condominium_admunit (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES condominium ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE basicpropertyunit (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    nationalcadastralreference text,
    areavalue numeric,
    areavalue_attr_nilreason text,
    areavalue_attr_uom text,
    areavalue_attr_nil boolean,
    validfrom timestamp,
    validfrom_attr_nilreason text,
    validfrom_attr_nil boolean,
    validto timestamp,
    validto_attr_nilreason text,
    validto_attr_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    administrativeunit_attr_owns boolean,
    administrativeunit_attr_nilreason text,
    administrativeunit_attr_remoteschema text,
    administrativeunit_attr_nil boolean,
    administrativeunit_fk text,
    administrativeunit_href text,
    CONSTRAINT basicpropertyunit_pkey PRIMARY KEY (gid)
);
CREATE TABLE cadastralboundary (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    estimatedaccuracy numeric,
    estimatedaccuracy_attr_nilreason text,
    estimatedaccuracy_attr_uom text,
    estimatedaccuracy_attr_nil boolean,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    validfrom timestamp,
    validfrom_attr_nilreason text,
    validfrom_attr_nil boolean,
    validto timestamp,
    validto_attr_nilreason text,
    validto_attr_nil boolean,
    CONSTRAINT cadastralboundary_pkey PRIMARY KEY (gid)
);
SELECT ADDGEOMETRYCOLUMN('', 'cadastralboundary','geometry_value','0','GEOMETRY', 2);
CREATE TABLE cadastralboundary_parcel (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES cadastralboundary ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE cadastralparcel (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    areavalue numeric,
    areavalue_attr_nilreason text,
    areavalue_attr_uom text,
    areavalue_attr_nil boolean,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    label text,
    nationalcadastralreference text,
    referencepoint_attr_nilreason text,
    referencepoint_attr_remoteschema text,
    referencepoint_attr_owns boolean,
    referencepoint_attr_nil boolean,
    validfrom timestamp,
    validfrom_attr_nilreason text,
    validfrom_attr_nil boolean,
    validto timestamp,
    validto_attr_nilreason text,
    validto_attr_nil boolean,
    administrativeunit_attr_owns boolean,
    administrativeunit_attr_nilreason text,
    administrativeunit_attr_remoteschema text,
    administrativeunit_attr_nil boolean,
    administrativeunit_fk text,
    administrativeunit_href text,
    zoning_attr_owns boolean,
    zoning_attr_nilreason text,
    zoning_attr_remoteschema text,
    zoning_attr_nil boolean,
    zoning_fk text,
    zoning_href text,
    CONSTRAINT cadastralparcel_pkey PRIMARY KEY (gid)
);
SELECT ADDGEOMETRYCOLUMN('', 'cadastralparcel','geometry_value','0','GEOMETRY', 2);
SELECT ADDGEOMETRYCOLUMN('', 'cadastralparcel','referencepoint_value','0','GEOMETRY', 2);
CREATE TABLE cadastralparcel_basicpropertyunit (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES cadastralparcel ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);
CREATE TABLE cadastralzoning (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    estimatedaccuracy numeric,
    estimatedaccuracy_attr_nilreason text,
    estimatedaccuracy_attr_uom text,
    estimatedaccuracy_attr_nil boolean,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    label text,
    level_attr_owns boolean,
    level_attr_nilreason text,
    level_attr_remoteschema text,
    level_attr_nil boolean,
    level_fk text,
    level_href text,
    nationalcadastalzoningreference text,
    originalmapscaledenominator integer,
    originalmapscaledenominator_attr_nilreason text,
    originalmapscaledenominator_attr_nil boolean,
    referencepoint_attr_nilreason text,
    referencepoint_attr_remoteschema text,
    referencepoint_attr_owns boolean,
    referencepoint_attr_nil boolean,
    validfrom timestamp,
    validfrom_attr_nilreason text,
    validfrom_attr_nil boolean,
    validto timestamp,
    validto_attr_nilreason text,
    validto_attr_nil boolean,
    upperlevelunit_attr_owns boolean,
    upperlevelunit_attr_nilreason text,
    upperlevelunit_attr_remoteschema text,
    upperlevelunit_attr_nil boolean,
    upperlevelunit_fk text,
    upperlevelunit_href text,
    CONSTRAINT cadastralzoning_pkey PRIMARY KEY (gid)
);
SELECT ADDGEOMETRYCOLUMN('', 'cadastralzoning','geometry_value','0','GEOMETRY', 2);
CREATE TABLE cadastralzoning_levelname (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES cadastralzoning ON DELETE CASCADE,
    num integer not null,
    attr_type text,
    attr_href text,
    attr_role text,
    attr_arcrole text,
    attr_title text,
    attr_show text,
    attr_actuate text,
    attr_uuidref text,
    attr_nilreason text,
    attr_nil boolean,
    localisedcharacterstring text,
    localisedcharacterstring_attr_id text,
    localisedcharacterstring_attr_locale text
);
CREATE TABLE cadastralzoning_name (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES cadastralzoning ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_nil boolean,
    geographicalname_language text,
    geographicalname_language_attr_nilreason text,
    geographicalname_language_attr_nil boolean,
    geographicalname_nativeness_attr_owns boolean,
    geographicalname_nativeness_attr_nilreason text,
    geographicalname_nativeness_attr_remoteschema text,
    geographicalname_nativeness_attr_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_attr_owns boolean,
    geographicalname_namestatus_attr_nilreason text,
    geographicalname_namestatus_attr_remoteschema text,
    geographicalname_namestatus_attr_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_attr_nilreason text,
    geographicalname_sourceofname_attr_nil boolean,
    geographicalname_pronunciation_attr_nilreason text,
    geographicalname_pronunciation_attr_nil boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_51 text,
    geographicalname_pronunciation_pronunciationofname_pronun_52 text,
    geographicalname_pronunciation_pronunciationofname_pronun_53 boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_54 text,
    geographicalname_pronunciation_pronunciationofname_pronun_55 text,
    geographicalname_pronunciation_pronunciationofname_pronun_56 boolean,
    geographicalname_grammaticalgender_attr_owns boolean,
    geographicalname_grammaticalgender_attr_nilreason text,
    geographicalname_grammaticalgender_attr_remoteschema text,
    geographicalname_grammaticalgender_attr_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_attr_owns boolean,
    geographicalname_grammaticalnumber_attr_nilreason text,
    geographicalname_grammaticalnumber_attr_remoteschema text,
    geographicalname_grammaticalnumber_attr_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text
);
CREATE TABLE cadastralzoning_name_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES cadastralzoning_name ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_attr_nilreason text,
    geographicalname_spellingofname_script_attr_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_att_57 text,
    geographicalname_spellingofname_transliterationscheme_attr_nil boolean
);
SELECT ADDGEOMETRYCOLUMN('', 'cadastralzoning','referencepoint_value','0','GEOMETRY', 2);
CREATE TABLE namedplace (
    gid serial,
    identifier text,
    identifier_attr_codespace text,
    beginlifespanversion timestamp,
    beginlifespanversion_attr_nilreason text,
    beginlifespanversion_attr_nil boolean,
    endlifespanversion timestamp,
    endlifespanversion_attr_nilreason text,
    endlifespanversion_attr_nil boolean,
    geometry_attr_nilreason text,
    geometry_attr_remoteschema text,
    geometry_attr_owns boolean,
    inspireid_identifier_localid text,
    inspireid_identifier_namespace text,
    inspireid_identifier_versionid text,
    inspireid_identifier_versionid_attr_nilreason text,
    inspireid_identifier_versionid_attr_nil boolean,
    leastdetailedviewingresolution_attr_nilreason text,
    leastdetailedviewingresolution_attr_owns boolean,
    leastdetailedviewingresolution_attr_nil boolean,
    leastdetailedviewingresolution_md_resolution_equivalentsc_58 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_59 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_60 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_61 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_62 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_63 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_64 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_65 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_66 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_68 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_69 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_71 text,
    leastdetailedviewingresolution_md_resolution_equivalentsc_72 integer,
    leastdetailedviewingresolution_md_resolution_distance_att_73 text,
    leastdetailedviewingresolution_md_resolution_distance_distance numeric,
    leastdetailedviewingresolution_md_resolution_distance_dis_74 text,
    mostdetailedviewingresolution_attr_nilreason text,
    mostdetailedviewingresolution_attr_owns boolean,
    mostdetailedviewingresolution_attr_nil boolean,
    mostdetailedviewingresolution_md_resolution_equivalentsca_75 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_76 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_77 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_78 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_79 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_80 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_81 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_82 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_83 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_85 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_86 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_88 text,
    mostdetailedviewingresolution_md_resolution_equivalentsca_89 integer,
    mostdetailedviewingresolution_md_resolution_distance_attr_90 text,
    mostdetailedviewingresolution_md_resolution_distance_distance numeric,
    mostdetailedviewingresolution_md_resolution_distance_dist_91 text,
    CONSTRAINT namedplace_pkey PRIMARY KEY (gid)
);
SELECT ADDGEOMETRYCOLUMN('', 'namedplace','geometry_value','0','GEOMETRY', 2);
CREATE TABLE namedplace_localtype (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES namedplace ON DELETE CASCADE,
    num integer not null,
    attr_type text,
    attr_href text,
    attr_role text,
    attr_arcrole text,
    attr_title text,
    attr_show text,
    attr_actuate text,
    attr_uuidref text,
    attr_nilreason text,
    attr_nil boolean,
    localisedcharacterstring text,
    localisedcharacterstring_attr_id text,
    localisedcharacterstring_attr_locale text
);
CREATE TABLE namedplace_name (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES namedplace ON DELETE CASCADE,
    num integer not null,
    geographicalname_language text,
    geographicalname_language_attr_nilreason text,
    geographicalname_language_attr_nil boolean,
    geographicalname_nativeness_attr_owns boolean,
    geographicalname_nativeness_attr_nilreason text,
    geographicalname_nativeness_attr_remoteschema text,
    geographicalname_nativeness_attr_nil boolean,
    geographicalname_nativeness_fk text,
    geographicalname_nativeness_href text,
    geographicalname_namestatus_attr_owns boolean,
    geographicalname_namestatus_attr_nilreason text,
    geographicalname_namestatus_attr_remoteschema text,
    geographicalname_namestatus_attr_nil boolean,
    geographicalname_namestatus_fk text,
    geographicalname_namestatus_href text,
    geographicalname_sourceofname text,
    geographicalname_sourceofname_attr_nilreason text,
    geographicalname_sourceofname_attr_nil boolean,
    geographicalname_pronunciation_attr_nilreason text,
    geographicalname_pronunciation_attr_nil boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_92 text,
    geographicalname_pronunciation_pronunciationofname_pronun_93 text,
    geographicalname_pronunciation_pronunciationofname_pronun_94 boolean,
    geographicalname_pronunciation_pronunciationofname_pronun_95 text,
    geographicalname_pronunciation_pronunciationofname_pronun_96 text,
    geographicalname_pronunciation_pronunciationofname_pronun_97 boolean,
    geographicalname_grammaticalgender_attr_owns boolean,
    geographicalname_grammaticalgender_attr_nilreason text,
    geographicalname_grammaticalgender_attr_remoteschema text,
    geographicalname_grammaticalgender_attr_nil boolean,
    geographicalname_grammaticalgender_fk text,
    geographicalname_grammaticalgender_href text,
    geographicalname_grammaticalnumber_attr_owns boolean,
    geographicalname_grammaticalnumber_attr_nilreason text,
    geographicalname_grammaticalnumber_attr_remoteschema text,
    geographicalname_grammaticalnumber_attr_nil boolean,
    geographicalname_grammaticalnumber_fk text,
    geographicalname_grammaticalnumber_href text
);
CREATE TABLE namedplace_name_geographicalname_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES namedplace_name ON DELETE CASCADE,
    num integer not null,
    geographicalname_spellingofname_text text,
    geographicalname_spellingofname_script text,
    geographicalname_spellingofname_script_attr_nilreason text,
    geographicalname_spellingofname_script_attr_nil boolean,
    geographicalname_spellingofname_transliterationscheme text,
    geographicalname_spellingofname_transliterationscheme_att_98 text,
    geographicalname_spellingofname_transliterationscheme_attr_nil boolean
);
CREATE TABLE namedplace_relatedspatialobject (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES namedplace ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_nil boolean,
    identifier_localid text,
    identifier_namespace text,
    identifier_versionid text,
    identifier_versionid_attr_nilreason text,
    identifier_versionid_attr_nil boolean
);
CREATE TABLE namedplace_type (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES namedplace ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_remoteschema text,
    attr_nil boolean,
    fk text,
    href text
);