CREATE TABLE gn_namedplace (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    gn_beginlifespanversion timestamp,
    gn_beginlifespanversion_attr_nilreason text,
    gn_beginlifespanversion_attr_xsi_nil boolean,
    gn_endlifespanversion timestamp,
    gn_endlifespanversion_attr_nilreason text,
    gn_endlifespanversion_attr_xsi_nil boolean,
    gn_geometry_attr_nilreason text,
    gn_geometry_attr_gml_remoteschema text,
    gn_geometry_attr_owns boolean,
    gn_inspireid_base_identifier_base_localid text,
    gn_inspireid_base_identifier_base_namespace text,
    gn_inspireid_base_identifier_base_versionid text,
    gn_inspireid_base_identifier_base_versionid_attr_nilreason text,
    gn_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_attr_nilreason text,
    gn_leastdetailedviewingresolution_attr_owns boolean,
    gn_leastdetailedviewingresolution_attr_xsi_nil boolean,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_201 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_202 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_203 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_204 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_205 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_206 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_207 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_208 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_209 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_211 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_212 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_214 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_eq_215 integer,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_di_217 text,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_di_218 numeric,
    gn_leastdetailedviewingresolution_gmd_md_resolution_gmd_di_219 text,
    gn_mostdetailedviewingresolution_attr_nilreason text,
    gn_mostdetailedviewingresolution_attr_owns boolean,
    gn_mostdetailedviewingresolution_attr_xsi_nil boolean,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_221 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_222 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_223 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_224 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_225 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_226 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_227 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_228 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_229 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_231 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_232 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_234 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_equ_235 integer,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_dis_236 text,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_dis_237 numeric,
    gn_mostdetailedviewingresolution_gmd_md_resolution_gmd_dis_238 text,
    CONSTRAINT gn_namedplace_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'gn_namedplace','gn_geometry_value','4326','GEOMETRY', 2);
CREATE TABLE gn_namedplace_gn_localtype (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_xlink_type text,
    attr_xlink_href text,
    attr_xlink_role text,
    attr_xlink_arcrole text,
    attr_xlink_title text,
    attr_xlink_show text,
    attr_xlink_actuate text,
    attr_uuidref text,
    attr_gco_nilreason text,
    attr_xsi_nil boolean,
    gmd_localisedcharacterstring text,
    gmd_localisedcharacterstring_attr_id text,
    gmd_localisedcharacterstring_attr_locale text
);
CREATE TABLE gn_namedplace_gn_name (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_239 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_240 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_241 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_242 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_243 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_244 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE gn_namedplace_gn_name_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES gn_namedplace_gn_name ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterationsc_245 text,
    gn_geographicalname_gn_spellingofname_gn_transliterationsc_246 boolean
);
CREATE TABLE gn_namedplace_gn_relatedspatialobject (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    base_identifier_base_localid text,
    base_identifier_base_namespace text,
    base_identifier_base_versionid text,
    base_identifier_base_versionid_attr_nilreason text,
    base_identifier_base_versionid_attr_xsi_nil boolean
);
CREATE TABLE gn_namedplace_gn_type (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES gn_namedplace ON DELETE CASCADE,
    num integer not null,
    attr_owns boolean,
    attr_nilreason text,
    attr_gml_remoteschema text,
    attr_xsi_nil boolean,
    fk text,
    href text
);
CREATE TABLE ps_protectedsite (
    attr_gml_id text,
    gml_identifier text,
    gml_identifier_attr_codespace text,
    ps_geometry_attr_nilreason text,
    ps_geometry_attr_gml_remoteschema text,
    ps_geometry_attr_owns boolean,
    ps_inspireid_base_identifier_base_localid text,
    ps_inspireid_base_identifier_base_namespace text,
    ps_inspireid_base_identifier_base_versionid text,
    ps_inspireid_base_identifier_base_versionid_attr_nilreason text,
    ps_inspireid_base_identifier_base_versionid_attr_xsi_nil boolean,
    ps_legalfoundationdate timestamp,
    ps_legalfoundationdate_attr_nilreason text,
    ps_legalfoundationdate_attr_xsi_nil boolean,
    ps_legalfoundationdocument_attr_nilreason text,
    ps_legalfoundationdocument_attr_owns boolean,
    ps_legalfoundationdocument_attr_xsi_nil boolean,
    ps_legalfoundationdocument_gmd_ci_citation_attr_id text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_uuid text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_title_attr__0 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_title_gco_c_1 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_edition_att_14 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_edition_gco_15 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_editiondate_16 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_editiondate_17 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_editiondate_18 timestamp,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_162 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_163 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_164 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_165 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_166 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_167 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_168 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_169 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_attr_170 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__172 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__173 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__175 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__176 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__178 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__179 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__181 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_series_gmd__182 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_othercitati_184 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_othercitati_185 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_collectivet_186 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_collectivet_187 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_isbn_attr_g_188 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_isbn_gco_ch_189 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_issn_attr_g_190 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_issn_gco_ch_191 text,
    CONSTRAINT ps_protectedsite_pkey PRIMARY KEY (attr_gml_id)
);
SELECT ADDGEOMETRYCOLUMN('', 'ps_protectedsite','ps_geometry_value','4326','GEOMETRY', 2);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_2 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_attr_gco_nilreason text,
    ps_legalfoundationdocument_gmd_ci_citation_gco_characterstring text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_3 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_type text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_href text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_role text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_arcrole text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_title text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_show text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_actuate text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_uuidref text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_gco_nilreason text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_attr_id text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_att_4 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_5 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_6 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_7 timestamp,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_9 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_10 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_11 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_12 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_date_gmd_13 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_19 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_type text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_href text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_role text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_arcrole text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_title text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_show text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_actuate text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_uuidref text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_gco_nilreason text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_20 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_21 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_23 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_24 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_25 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_26 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_27 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_28 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_29 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_30 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_31 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_33 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_md_identifi_34 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_35 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_type text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_href text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_role text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_arcrole text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_title text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_show text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_xlink_actuate text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_uuidref text,
    ps_legalfoundationdocument_gmd_ci_citation_attr_gco_nilreason text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_37 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_38 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_40 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_41 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_43 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_44 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_46 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_47 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_49 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_50 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_51 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_52 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_53 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_54 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_55 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_56 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_57 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_59 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_60 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_62 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_63 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_64 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_65 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_66 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_67 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_68 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_69 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_70 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_72 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_73 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_81 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_82 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_83 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_84 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_85 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_86 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_87 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_88 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_89 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_91 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_92 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_97 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_98 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_100 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_101 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_103 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_104 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_106 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_107 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_112 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_113 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_114 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_115 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_116 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_117 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_118 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_119 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_120 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_122 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_123 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_125 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_126 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_128 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_129 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_131 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_132 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_134 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_135 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_137 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_138 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_140 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_141 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_142 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_143 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_144 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_146 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_147 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_149 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_150 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_152 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_153 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_154 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_155 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_156 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_74 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_35 ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_75 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_76 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_77 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_35 ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_78 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_79 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_93 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_35 ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_94 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_95 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_108 (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_35 ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_109 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_responsi_110 text
);
CREATE TABLE ps_protectedsite_ps_legalfoundationdocument_gmd_ci_citatio_157 (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    ps_legalfoundationdocument_gmd_ci_citation_attr_gco_nilreason text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_presenta_158 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_presenta_159 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_presenta_160 text,
    ps_legalfoundationdocument_gmd_ci_citation_gmd_ci_presenta_161 text
);
CREATE TABLE ps_protectedsite_ps_sitedesignation (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    ps_designationtype_ps_designationscheme_attr_owns boolean,
    ps_designationtype_ps_designationscheme_attr_nilreason text,
    ps_designationtype_ps_designationscheme_attr_gml_remoteschema text,
    ps_designationtype_ps_designationscheme_fk text,
    ps_designationtype_ps_designationscheme_href text,
    ps_designationtype_ps_designation_attr_owns boolean,
    ps_designationtype_ps_designation_attr_nilreason text,
    ps_designationtype_ps_designation_attr_gml_remoteschema text,
    ps_designationtype_ps_designation_fk text,
    ps_designationtype_ps_designation_href text,
    ps_designationtype_ps_percentageunderdesignation numeric
);
CREATE TABLE ps_protectedsite_ps_sitename (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    attr_nilreason text,
    attr_xsi_nil boolean,
    gn_geographicalname_gn_language text,
    gn_geographicalname_gn_language_attr_nilreason text,
    gn_geographicalname_gn_language_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_attr_owns boolean,
    gn_geographicalname_gn_nativeness_attr_nilreason text,
    gn_geographicalname_gn_nativeness_attr_gml_remoteschema text,
    gn_geographicalname_gn_nativeness_attr_xsi_nil boolean,
    gn_geographicalname_gn_nativeness_fk text,
    gn_geographicalname_gn_nativeness_href text,
    gn_geographicalname_gn_namestatus_attr_owns boolean,
    gn_geographicalname_gn_namestatus_attr_nilreason text,
    gn_geographicalname_gn_namestatus_attr_gml_remoteschema text,
    gn_geographicalname_gn_namestatus_attr_xsi_nil boolean,
    gn_geographicalname_gn_namestatus_fk text,
    gn_geographicalname_gn_namestatus_href text,
    gn_geographicalname_gn_sourceofname text,
    gn_geographicalname_gn_sourceofname_attr_nilreason text,
    gn_geographicalname_gn_sourceofname_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_attr_nilreason text,
    gn_geographicalname_gn_pronunciation_attr_xsi_nil boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_192 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_193 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_194 boolean,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_195 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_196 text,
    gn_geographicalname_gn_pronunciation_gn_pronunciationofnam_197 boolean,
    gn_geographicalname_gn_grammaticalgender_attr_owns boolean,
    gn_geographicalname_gn_grammaticalgender_attr_nilreason text,
    gn_geographicalname_gn_grammaticalgender_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalgender_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalgender_fk text,
    gn_geographicalname_gn_grammaticalgender_href text,
    gn_geographicalname_gn_grammaticalnumber_attr_owns boolean,
    gn_geographicalname_gn_grammaticalnumber_attr_nilreason text,
    gn_geographicalname_gn_grammaticalnumber_attr_gml_remoteschema text,
    gn_geographicalname_gn_grammaticalnumber_attr_xsi_nil boolean,
    gn_geographicalname_gn_grammaticalnumber_fk text,
    gn_geographicalname_gn_grammaticalnumber_href text
);
CREATE TABLE ps_protectedsite_ps_sitename_gn_geographicalname_gn_spelling (
    id serial PRIMARY KEY,
    parentfk integer NOT NULL REFERENCES ps_protectedsite_ps_sitename ON DELETE CASCADE,
    num integer not null,
    gn_geographicalname_gn_spellingofname_gn_text text,
    gn_geographicalname_gn_spellingofname_gn_script text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_nilreason text,
    gn_geographicalname_gn_spellingofname_gn_script_attr_xsi_nil boolean,
    gn_geographicalname_gn_spellingofname_gn_transliterationscheme text,
    gn_geographicalname_gn_spellingofname_gn_transliterationsc_198 text,
    gn_geographicalname_gn_spellingofname_gn_transliterationsc_199 boolean
);
CREATE TABLE ps_protectedsite_ps_siteprotectionclassification (
    id serial PRIMARY KEY,
    parentfk text NOT NULL REFERENCES ps_protectedsite ON DELETE CASCADE,
    num integer not null,
    value text,
    attr_nilreason text,
    attr_xsi_nil boolean
);